In [4]:
import numpy as np

## Data types and Attribute

In [5]:
#Numpy's main data type is ndarray
a1 = np.array ([1 , 2 , 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1 ,2.0 ,3.3],
               [4, 5, 6.5]])
a3 = np.array ([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
# Create a dataframe from a Numpyarray
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays



In [16]:
sample_array = np.array ([1,2,3])
sample_array


array([1, 2, 3])

In [17]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array=np.random.randint(0, 8, size=(3,6))
random_array

array([[2, 2, 1, 7, 0, 3],
       [4, 1, 0, 5, 2, 0],
       [5, 3, 1, 6, 0, 2]])

#Pseudo random

In [19]:
random_array_4= np.random.randint(10 , size=(5,3,3))
random_array_4

array([[[6, 1, 4],
        [0, 2, 1],
        [6, 3, 2]],

       [[4, 6, 5],
        [7, 7, 1],
        [6, 0, 7]],

       [[5, 1, 5],
        [0, 7, 0],
        [6, 4, 2]],

       [[0, 0, 8],
        [7, 6, 1],
        [6, 4, 3]],

       [[0, 5, 1],
        [9, 7, 9],
        [5, 3, 9]]])

## Viewing Arrays and Matrices

In [20]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
random_array_4

array([[[6, 1, 4],
        [0, 2, 1],
        [6, 3, 2]],

       [[4, 6, 5],
        [7, 7, 1],
        [6, 0, 7]],

       [[5, 1, 5],
        [0, 7, 0],
        [6, 4, 2]],

       [[0, 0, 8],
        [7, 6, 1],
        [6, 4, 3]],

       [[0, 5, 1],
        [9, 7, 9],
        [5, 3, 9]]])

In [24]:
random_array_4.shape

(5, 3, 3)

In [25]:
random_array_4[: , : , :2]

array([[[6, 1],
        [0, 2],
        [6, 3]],

       [[4, 6],
        [7, 7],
        [6, 0]],

       [[5, 1],
        [0, 7],
        [6, 4]],

       [[0, 0],
        [7, 6],
        [6, 4]],

       [[0, 5],
        [9, 7],
        [5, 3]]])

In [26]:
random_array_4[:3 ,: , :]

array([[[6, 1, 4],
        [0, 2, 1],
        [6, 3, 2]],

       [[4, 6, 5],
        [7, 7, 1],
        [6, 0, 7]],

       [[5, 1, 5],
        [0, 7, 0],
        [6, 4, 2]]])

## Manipulating and Comparing Arrays
## Arithmetic


In [27]:
a1


array([1, 2, 3])

In [28]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [29]:
a1 + ones

array([2., 3., 4.])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a1*a2


array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [32]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

## Aggregation

In [33]:
sum(a1)

6

In [34]:
np.sum(a1)


6

In [35]:
np.max(a2)

6.5

In [36]:
np.std(a3)

5.188127472091127

In [37]:
np.var(a2)

3.3222222222222224

# Reshaping and Transposing

In [40]:
a2_reshape = a2.reshape(2,3,1)

In [41]:
a2_reshape


array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [42]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

# Dot Product

In [45]:
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1

array([[7, 1, 4],
       [7, 1, 5],
       [6, 8, 3],
       [9, 1, 0],
       [0, 1, 1]])

In [46]:
mat1

array([[7, 1, 4],
       [7, 1, 5],
       [6, 8, 3],
       [9, 1, 0],
       [0, 1, 1]])

In [47]:
mat2

array([[0, 5, 6],
       [5, 7, 4],
       [7, 6, 7],
       [1, 5, 7],
       [0, 3, 1]])

In [48]:
mat2.T


array([[0, 5, 7, 1, 0],
       [5, 7, 6, 5, 3],
       [6, 4, 7, 7, 1]])

In [51]:
mat1.shape , mat2.T.shape

((5, 3), (3, 5))

In [56]:
mat3 = np.dot(mat1 , mat2.T)

In [58]:
mat3

array([[ 29,  58,  83,  40,   7],
       [ 35,  62,  90,  47,   8],
       [ 58,  98, 111,  67,  27],
       [  5,  52,  69,  14,   3],
       [ 11,  11,  13,  12,   4]])

In [62]:
np.random.seed(0)
# Number of jar sold
sales_amount= np.random.randint(20 , size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])